//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEverNote.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Comment : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comment()
        {
            this.CommentLike = new HashSet<CommentLike>();
        }
    
        public int Id { get; set; }
        [Required]
        public string Text { get; set; }
        public int LikeCount { get; set; }
        [Required]
        public int OwnerId { get; set; }
        [Required]
        public int NoteId { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime CreateOn { get; set; }
        public System.DateTime ModifieOn { get; set; }
    
        public virtual EverNoteUser EverNoteUser { get; set; }
        public virtual Note Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentLike> CommentLike { get; set; }
    }
}
