//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEverNote.Entities
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class EverNoteUser : EntityBase
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EverNoteUser()
        {
            this.Comment = new HashSet<Comment>();
            this.CommentLike = new HashSet<CommentLike>();
            this.Note = new HashSet<Note>();
            this.NoteLike = new HashSet<NoteLike>();
        }
        
        
        public int Id { get; set; }
        [Required,MaxLength(15,ErrorMessage ="Name alaný maximum {1} karakter olmalýdýr.")]
        public string Name { get; set; }
        [Required, MaxLength(30, ErrorMessage = "Surname alaný maximum {1} karakter olmalýdýr.")]
        public string Surname { get; set; }
        [Required, MaxLength(15, ErrorMessage = "Username alaný maximum {1} karakter olmalýdýr.")]
        public string Username { get; set; }
        [Required,MaxLength(8, ErrorMessage = "Username alaný maximum {1} karakter olmalýdýr."),DataType(DataType.Password)]
        public string Password { get; set; }
        [Required,EmailAddress(ErrorMessage ="Geçerli email formatý giriniz.")]
        public string Email { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdmin { get; set; }
        public string ActivateGuid { get; set; }
        public string ProfileImage { get; set; }
        public string ModifiedUser { get; set; }
        public System.DateTime CreateOn { get; set; }
        public System.DateTime ModifieOn { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommentLike> CommentLike { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Note> Note { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NoteLike> NoteLike { get; set; }
    }
}
