//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyEverNote.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NoteBookEntities : DbContext
    {
        public NoteBookEntities()
            : base("name=NoteBookEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Category> Category { get; set; }
        public virtual DbSet<Comment> Comment { get; set; }
        public virtual DbSet<CommentLike> CommentLike { get; set; }
        public virtual DbSet<EverNoteUser> EverNoteUser { get; set; }
        public virtual DbSet<Note> Note { get; set; }
        public virtual DbSet<NoteLike> NoteLike { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
